### ISSUE TITLE
Interaction with Brick MQTT Proxy?

### ISSUE THREAD

**Issue by wechsler42** [PlayWithIt/TFStubserver#2]
Hi there,
I wonder whether an interaction with the[ Brick MQTT Proxy](https://www.tinkerforge.com/en/doc/Software/Brick_MQTT_Proxy.html) and the TFStubserver is possible. If so, how would I do that?
Thanks in advance.

**Comment by PlayWithIt** [comment]
Since the stubserver works just like brickd (based on TCP/IP protocol) a communication should be possible.
Just configure MQTT to connect to the stubserver, so either configure the stubserver to use the brickd default port 4223 (option -p) or tell MQTT to connect to different port (4225 which is the default for the stubserver if -p is not used).
I didn't look into MQTT more detailed, but this should be possible.

**Comment by PlayWithIt** [comment]
The UI (TFStubViz) is not necessary, this is just for visualizing the state of the virtual devices.

**Comment by wechsler42** [comment]
Thank you very much PlayWithIt. It just works with the Brick MQTT Proxy as you described. Just have to take care on choosing the similar ports for both, the MQTT proxy and the TFStubserver.

**Comment by PlayWithIt** [comment]
recently updated to latest bindings and added support for CO2 and UV light bricklet
